// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterControl.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterControl::ShooterControl(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterSubsystem.get());

	buttonApressed = false;
	buttonBpressed = false;
	buttonXpressed = false;
	rightTriggerpressed = 0;
	leftTriggerpressed = 0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterControl::Initialize() {

	buttonApressed = false;
	buttonBpressed = false;
	buttonXpressed = false;
	rightTriggerpressed = 0;
	leftTriggerpressed = 0;
}

// Called repeatedly when this Command is scheduled to run
void ShooterControl::Execute() {

	buttonApressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(buttonApressed)
		{
			Robot::shooterSubsystem->Shoot(1);
		}
		else
		{
			Robot::shooterSubsystem->Shoot(0);
		}

	buttonBpressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(buttonBpressed)
		{
			Robot::shooterSubsystem->Shoot(1);
		}
		else
		{
			Robot::shooterSubsystem->Shoot(0);
		}

	buttonXpressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(buttonXpressed)
		{
			Robot::shooterSubsystem->Shoot(1);
		}
		else
		{
			Robot::shooterSubsystem->Shoot(0);
		}

	buttonYpressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(buttonYpressed)
		{
			Robot::shooterSubsystem->Shoot(1);
		}
		else
		{
		Robot::shooterSubsystem->Shoot(0);
		}
	leftTriggerpressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(leftTriggerpressed > 0 && leftTriggerpressed < 0)
		{
			Robot::shooterSubsystem->Shoot(1)
		}
		else
		{
			Robot::shooterSubsystem->Shoot(0)
		}
			rightTriggerpressed = Robot::oi->getGunnerJoystick()->GetRawButton(1);
		if(leftTriggerpressed > 0 && leftTriggerpressed < 0)
		{
			Robot::shooterSubsystem->Shoot(1)
		}
		else
		{
			Robot::shooterSubsystem->Shoot(0)
		}
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterControl::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ShooterControl::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterControl::Interrupted() {

}
